---
title: Claret.Tech
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: romain@claret.tech
description: Blockchain & Innovation Engineer, Speaker, Founder, Advisor, and Executive Director.
  Software Engineer specialized in P2P and Fully Autonomous Digital Agents. Technology
  Fanatic, Innovator, Utopist and driven by Disruption.
baseurl: ''
url: http://claret.tech
tiles-source: posts
tiles-count: 3
featured-image-source: 
500px_url: 
facebook_url: 
github_url: https://github.com/Rocla
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/romainclaret/
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/RomainClaret
21_url: https://21.co/romainclaret
keybase_url: 
markdown: kramdown
google_analytics: UA-74600637-4
plugins:
- jekyll-sitemap
